-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) 'YEAR'
      ,MONTH(SALES_DATE) 'MONTH'
      ,GENDER
      ,COUNT(DISTINCT OS.USER_ID) 'USERS'
 FROM USER_INFO UI
      INNER JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE) ,MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE) ,MONTH(SALES_DATE), GENDER 
