-- 코드를 입력하세요
WITH CTE AS(
SELECT *
      ,ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) rn
  FROM REST_INFO)
  
SELECT FOOD_TYPE
      ,REST_ID
      ,REST_NAME
      ,FAVORITES
  FROM CTE
 WHERE rn = 1
 ORDER BY FOOD_TYPE DESC