-- 코드를 입력하세요
WITH CTE AS(
SELECT *
      ,DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) rk
  FROM FOOD_PRODUCT
 WHERE CATEGORY IN ('과자', '국', '김치', '식용유'))
  
SELECT CATEGORY 
      ,PRICE 'MAX_PRICE'
      ,PRODUCT_NAME
  FROM FOOD_PRODUCT
 WHERE PRODUCT_NAME IN (SELECT PRODUCT_NAME
                          FROM CTE
                         WHERE rk = 1)
 ORDER BY PRICE DESC
