-- 코드를 입력하세요
SELECT FP.PRODUCT_ID
      ,PRODUCT_NAME
      ,PRICE * SUM(AMOUNT) TOTAL_SALES
  FROM FOOD_PRODUCT FP
       INNER JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
 WHERE PRODUCE_DATE BETWEEN '2022-05-01 00:00:00' AND '2022-05-31 23:59:59'
 GROUP BY FP.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID
 

